---
- homebrew:
    name: zsh

- lineinfile:
    path: /etc/shells
    line: /usr/local/bin/zsh
  become: true

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /usr/local/bin/zsh
    update_password: on_create
  become: true

- homebrew_tap:
    name: thoughtbot/formulae

- homebrew:
    name: rcm

- homebrew:
    name: antibody

- homebrew_cask:
    name: iterm2
