---
- name: Install zsh
  homebrew:
    name: zsh

- lineinfile:
    path: /etc/shells
    line: /usr/local/bin/zsh
  become: true
  when: ansible_facts['machine'] == 'x86_64'

- lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/zsh
  become: true
  when: ansible_facts['machine'] == 'aarch64'

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /usr/local/bin/zsh
    update_password: on_create
  become: true
  when: ansible_facts['machine'] == 'x86_64'

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /opt/homebrew/bin/zsh
    update_password: on_create
  become: true
  when: ansible_facts['machine'] == 'aarch64'

- homebrew_tap:
    name: thoughtbot/formulae

- homebrew:
    name: rcm

- homebrew:
    name: antibody

- homebrew:
    name: hub

- homebrew:
    name: neovim

- homebrew:
    name: coreutils

- homebrew:
    name: gpg2

- name: Install Google Chrome
  homebrew_cask:
    name: google-chrome

- name: Install iTerm2
  homebrew_cask:
    name: iterm2

- name: Install Jetbrains Toolbox
  homebrew_cask:
    name: jetbrains-toolbox

- name: Install divvy
  homebrew_cask:
    name: divvy

- name: Install notion
  homebrew_cask:
    name: notion

- name: Install todoist
  homebrew_cask:
    name: todoist

- homebrew_tap:
    name: homebrew/cask-versions

- name: Install Java Zulu 8
  homebrew_cask:
    name: zulu8

- name: Install Java Zulu 11
  homebrew_cask:
    name: zulu11

- name: Install Java Zulu 17
  homebrew_cask:
    name: zulu17

- import_tasks: docker.yml
