---
- homebrew:
    name: zsh

- lineinfile:
    path: /etc/shells
    line: /usr/local/bin/zsh
  become: true
  when: ansible_facts['machine'] == 'x86_64'

- lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/zsh
  become: true
  when: ansible_facts['machine'] == 'aarch64'

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /usr/local/bin/zsh
    update_password: on_create
  become: true
  when: ansible_facts['machine'] == 'x86_64'

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /opt/homebrew/bin/zsh
    update_password: on_create
  become: true
  when: ansible_facts['machine'] == 'aarch64'

- homebrew_tap:
    name: thoughtbot/formulae

- homebrew:
    name: rcm

- homebrew:
    name: antibody

- homebrew:
    name: hub

- homebrew:
    name: neovim

- homebrew:
    name: coreutils

- homebrew:
    name: gpg2

- homebrew_cask:
    name: google-chrome

- homebrew_cask:
    name: iterm2

- homebrew_cask:
    name: jetbrains-toolbox

- homebrew_cask:
    name: divvy

- homebrew_tap:
    name: homebrew/cask-versions

- homebrew_cask:
    name: zulu8

- homebrew_cask:
    name: zulu11

- homebrew_cask:
    name: zulu17