---
- name: Install zsh
  homebrew:
    name: zsh

- lineinfile:
    path: /etc/shells
    line: /usr/local/bin/zsh
  become: true
  when: ansible_facts['machine'] == 'x86_64'

- lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/zsh
  become: true
  when: ansible_facts['machine'] == 'aarch64'

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /usr/local/bin/zsh
    update_password: on_create
  become: true
  when: ansible_facts['machine'] == 'x86_64'

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /opt/homebrew/bin/zsh
    update_password: on_create
  become: true
  when: ansible_facts['machine'] == 'aarch64'

- homebrew_tap:
    name: thoughtbot/formulae

- homebrew:
    name: rcm

- homebrew:
    name: fzf

- homebrew:
    name: hub

- homebrew:
    name: neovim

- homebrew:
    name: coreutils

- homebrew:
    name: gpg2

- stat:
    path: "/Applications/Google Chrome.app"
  register: CHROME_APP_DIR

- name: Install Google Chrome
  homebrew_cask:
    name: google-chrome
  when: CHROME_APP_DIR.stat.exists == false

- name: Install iTerm2
  homebrew_cask:
    name: iterm2

- name: Install Jetbrains Toolbox
  homebrew_cask:
    name: jetbrains-toolbox

- name: Install VS Code
  homebrew_cask:
    name: visual-studio-code

- stat:
    path: "/Applications/Divvy.app"
  register: DIVVY_APP_DIR

- name: Install divvy
  homebrew_cask:
    name: divvy
  when: DIVVY_APP_DIR.stat.exists == false

- name: Install notion
  homebrew_cask:
    name: notion

- name: Install todoist
  homebrew_cask:
    name: todoist

- homebrew_tap:
    name: homebrew/cask-versions

- name: Install Java Zulu 8
  homebrew_cask:
    name: zulu8

- name: Install Java Zulu 11
  homebrew_cask:
    name: zulu11

- name: Install Java Zulu 17
  homebrew_cask:
    name: zulu17

- name: Install Java Zulu 21
  homebrew_cask:
    name: zulu21

- import_tasks: docker.yml
