---
- homebrew:
    name: zsh

- lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/zsh
  become: true

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /opt/homebrew/bin/zsh
    update_password: on_create
  become: true

- homebrew_tap:
    name: thoughtbot/formulae

- homebrew:
    name: rcm

- homebrew:
    name: antibody

- homebrew:
    name: hub

- homebrew:
    name: neovim

- homebrew:
    name: coreutils

- homebrew:
    name: gpg2

- homebrew_cask:
    name: iterm2
