export XDG_CONFIG_HOME="${HOME}/.config"

export DEVBOX_DIR="${HOME}/.local/opt/devbox"
export PRIVATE_DEVBOX_DIR="${HOME}/.local/opt/devbox-private"
export DOTFILES_DIR="${HOME}/.local/opt/devbox/dotfiles"
export ANTIDOTE_DIR="${HOME}/.local/opt/antidote"

export EDITOR=nvim

if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

autoload -Uz compinit
DATE_CMD=date
if type gdate >/dev/null 2>&1; then
    DATE_CMD=gdate
fi

[ ! -e "~/.zcompdump" ] && compinit -i
if [ $($DATE_CMD +'%j') != $($DATE_CMD +'%j' -r ~/.zcompdump) ]; then
    compinit -i
else
    compinit -C -i
fi

for alias_file in $(ls ${HOME}/.local/lib/aliases/); do
    source "${HOME}/.local/lib/aliases/${alias_file}"
done

for include_file in $(ls ${HOME}/.local/lib/zsh-includes/); do
    source "${HOME}/.local/lib/zsh-includes/${include_file}"
done

if [[ -d "${ANTIDOTE_DIR}" ]]; then
    source "${ANTIDOTE_DIR}/antidote.zsh"
fi

if [[ -s "${HOME}/.config/antidote/plugins.zsh" ]]; then
    source "${HOME}/.config/antidote/plugins.zsh"
else
    eval "$(antidote bundle devinsba/zsh-plugins)"
    update_antidote_plugin_cache
    source "${HOME}/.config/antidote/plugins.zsh"
fi

export PATH="${HOME}/.local/bin:${PATH}"
[ -d "/snap/bin" ] && export PATH="${PATH}:/snap/bin"

if [[ -s "${HOME}/.zshrc_private" ]]; then
    source "${HOME}/.zshrc_private"
fi

if [[ -s "${HOME}/.zshrc_local" ]]; then
    source "${HOME}/.zshrc_local"
fi

# google-cloud-sdk brew caveat
if [[ -d "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/" ]]; then
    source "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc"
    source "/opt/homebrew/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc"
fi

