---
- stat:
    path: "{{ lookup('env','HOME') }}/.local/opt/sdkman"
  register: SDKMAN_DIR

- shell: |
    export SDKMAN_DIR="{{ lookup('env','HOME') }}/.local/opt/sdkman"
    curl -s "https://get.sdkman.io?rcupdate=false" | zsh
  when: SDKMAN_DIR.stat.exists == false