---
- apt_repository:
    repo: deb https://apt.thoughtbot.com/debian/ stable main
    filename: thoughtbot
    state: present

- name: Install a list of packages
  apt:
    pkg:
    - zsh
    - gnupg2
    - rcm