---
- name: Install a list of packages
  apt:
    pkg:
    - zsh
    - gnupg2
    - rcm
    - unzip
    - zip
    - hub
    - neovim
  become: true

- name: Install antibody
  apt:
    deb: https://github.com/getantibody/antibody/releases/download/v6.1.1/antibody_6.1.1_linux_amd64.deb
  become: true

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /usr/bin/zsh
    update_password: on_create
  become: true
