---
- name: Install a list of packages
  apt:
    pkg:
    - zsh
    - gnupg2
    - rcm
    - fzf
    - unzip
    - zip
    - hub
    - neovim
    - direnv
    - python3-debian
  become: true

- name: Add GitHub CLI apt repository
  deb822_repository:
    name: github-cli
    types: deb
    uris: https://cli.github.com/packages
    suites: stable
    components: main
    architectures: "{{ 'arm64' if ansible_facts['architecture'] == 'aarch64' else 'amd64' }}"
    signed_by: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    enabled: true
    state: present
  become: true

- name: Install GitHub CLI
  apt:
    name: gh
    update_cache: true
  become: true

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /usr/bin/zsh
    update_password: on_create
  become: true
