---
- apt_repository:
    repo: deb https://apt.thoughtbot.com/debian/ stable main
    filename: thoughtbot
    state: present

- name: Install a list of packages
  apt:
    pkg:
    - zsh
    - gnupg2
    - rcm

- name: Install antibody
  apt:
    deb: https://github.com/getantibody/antibody/releases/download/v6.0.1/antibody_6.0.1_linux_amd64.deb
  become: true

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /usr/bin/zsh
    update_password: on_create
  become: true