---
- name: Install a list of packages
  apt:
    pkg:
    - zsh
    - gnupg2
    - rcm
    - fzf
    - unzip
    - zip
    - hub
    - neovim
  become: true

- user:
    name: "{{ ansible_facts.user_id }}"
    create_home: no
    shell: /usr/bin/zsh
    update_password: on_create
  become: true
