- hosts: local
  roles:
    - role: osx
      when: ansible_facts['os_family'] == 'Darwin'
    - role: debian
      when: ansible_facts['os_family'] == 'Debian'
    - role: antidote
    - role: nvm
    - role: pyenv
    - role: rvm
    - role: sdkman
