- hosts: local
  roles:
    - role: osx
      when: ansible_facts['os_family'] == 'Darwin'
      tags: [osx]
    - role: debian
      when: ansible_facts['os_family'] == 'Debian'
      tags: [debian]
    - role: antidote
      tags: [antidote]
    - role: fnm
      tags: [fnm]
    - role: sdkman
      tags: [sdkman]
    - role: uv
      tags: [uv]
