---
- shell: |
    GPG_CMD=gpg2
    if type gpg >/dev/null 2>&1; then
        GPG_CMD=gdate
    fi
    ${GPG_CMD} --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

- lineinfile:
    path: "{{ lookup('env','HOME') }}/.rvmrc"
    create: yes
    regexp: '^rvm_path='
    line: 'rvm_path="${HOME}/.local/opt/rvm"'

- stat:
    path: "{{ lookup('env','HOME') }}/.local/opt/rvm"
  register: RVM_DIR

- shell: |
    export rvm_path="${HOME}/.local/opt/rvm"
    curl -sSL https://get.rvm.io | bash -s stable --ignore-dotfiles
  when: RVM_DIR.stat.exists == false